site_name: Self Build Motor Home
site_author: Michal Nezerka
theme:
  name: material
#  palette:
#    primary: 'blue'
#    accent: 'orange'
  features:
    - tabs
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
nav:
- Úvod: index.md
- Elektroinstalace: electricity.md
- Zabezpečení: security.md
- Karosérie (okna, hluk, teplo): body.md
- Legalizace: legalization.md
- Tips:
  - Honza K: tips/honza_k/index.md
  - nomadem.cz: tips/nomadem_cz/index.md
  - "L & M": tips/l_and_m/index.md
- Ducato: ducato.md
- Zdroje informací: resources.md
- "Mé auto":
  - Přehled: my/index.md
copyright: Copyright &copy; 2020 Michal Nezerka

