site_name: Self Build Motor Home
site_author: Michal Nezerka
theme:
  name: material
#  palette:
#    primary: 'blue'
#    accent: 'orange'
  features:
#    - tabs
#    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
markdown_extensions:
  - attr_list
nav:
- Úvod: index.md
- Elektroinstalace: electricity.md
- Zabezpečení: security.md
- Karosérie:
  - Odhlučnění a izolace: body.md
  - Okna: windows.md
- Postele:
  - Zvedací - upínací lišty: beds/clamping_rails.md
  - Zvedací - Two In One: beds/two_in_one.md
- Legalizace: legalization.md
- Tips:
  - Honza K: tips/honza_k/index.md
  - nomadem.cz: tips/nomadem_cz/index.md
  - "L & M": tips/l_and_m/index.md
- Zdroje informací: resources.md
- "Mé auto":
  - Přehled: my/index.md
copyright: Copyright &copy; 2020 Michal Nezerka

